# Generated by Django 2.1.1 on 2018-09-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('shoes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('shoes_type', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_before', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.FileField(upload_to='')),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shoes')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=15)),
                ('stock', models.BooleanField()),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shoes')),
            ],
        ),
    ]
